// <auto-generated />
using LabbAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabbAPI.Migrations
{
    [DbContext(typeof(PersonDbContext))]
    [Migration("20250422062837_addSeedData")]
    partial class addSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabbAPI.Models.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Loves to code in C# and JavaScript.",
                            Title = "Coding"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Enjoys both competitive and casual gaming.",
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Plays the guitar and enjoys rock music.",
                            Title = "Music"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Records videos for fun.",
                            Title = "Video"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Loves to exercise aims to becomes the next Arnold.",
                            Title = "Exercise"
                        });
                });

            modelBuilder.Entity("LabbAPI.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kim@example.com",
                            FirstName = "Kim",
                            LastName = "Andersson",
                            Telefonnummer = "0701234560"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sara@example.com",
                            FirstName = "Sara",
                            LastName = "Nilsson",
                            Telefonnummer = "0701234561"
                        },
                        new
                        {
                            Id = 3,
                            Email = "kalle@example.com",
                            FirstName = "Kalle",
                            LastName = "Johansson",
                            Telefonnummer = "0701234562"
                        },
                        new
                        {
                            Id = 4,
                            Email = "josefine@example.com",
                            FirstName = "Josefine",
                            LastName = "Svärd",
                            Telefonnummer = "0701234563"
                        },
                        new
                        {
                            Id = 5,
                            Email = "max@example.com",
                            FirstName = "Max",
                            LastName = "Bengtsson",
                            Telefonnummer = "0701234564"
                        });
                });

            modelBuilder.Entity("LabbAPI.Models.PersonInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            InterestId = 2,
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            InterestId = 3,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 4,
                            InterestId = 4,
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            InterestId = 3,
                            PersonId = 3
                        },
                        new
                        {
                            Id = 6,
                            InterestId = 5,
                            PersonId = 4
                        },
                        new
                        {
                            Id = 7,
                            InterestId = 2,
                            PersonId = 5
                        },
                        new
                        {
                            Id = 8,
                            InterestId = 1,
                            PersonId = 5
                        });
                });

            modelBuilder.Entity("LabbAPI.Models.PersonInterest", b =>
                {
                    b.HasOne("LabbAPI.Models.Interest", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LabbAPI.Models.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("LabbAPI.Models.Interest", b =>
                {
                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("LabbAPI.Models.Person", b =>
                {
                    b.Navigation("PersonInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
